name: smartstep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.2
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  custom_refresh_indicator: ^3.1.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.1
  fluttertoast: ^8.2.4
  convert: ^3.1.1
  shared_preferences: ^2.2.2
  excel: ^4.0.3
  path_provider: ^2.1.2
  lottie: ^3.1.0
  firebase_core: ^2.30.1
  path: any
  firebase_database: ^10.5.4
  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

