// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfh0riGaiABGH5xtydj9kIhA4CDXpjHvo',
    appId: '1:780015876055:web:437de83cb150d0e9b2fd92',
    messagingSenderId: '780015876055',
    projectId: 'smartstep-6a479',
    authDomain: 'smartstep-6a479.firebaseapp.com',
    storageBucket: 'smartstep-6a479.appspot.com',
    databaseURL: 'https://smartstep-6a479-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ06PZCMU_h6nmpO5Ew2rmtkigAH9TWzI',
    appId: '1:780015876055:android:000fc15dd0ab2cc2b2fd92',
    messagingSenderId: '780015876055',
    projectId: 'smartstep-6a479',
    storageBucket: 'smartstep-6a479.appspot.com',
    databaseURL: 'https://smartstep-6a479-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoeQtSgjMcBrKbs-nHARfiz7XqD_xGoNs',
    appId: '1:780015876055:ios:c2d759dac6eae7bab2fd92',
    messagingSenderId: '780015876055',
    projectId: 'smartstep-6a479',
    storageBucket: 'smartstep-6a479.appspot.com',
    iosBundleId: 'com.example.smartstep',
    databaseURL: 'https://smartstep-6a479-default-rtdb.firebaseio.com/'
  );

}